/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MatchingRouteImport } from './routes/matching'
import { Route as LobbyRouteImport } from './routes/lobby'
import { Route as InviteRouteImport } from './routes/invite'
import { Route as ConfirmRouteImport } from './routes/confirm'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CharacterIdRouteImport } from './routes/character.$id'

const MatchingRoute = MatchingRouteImport.update({
  id: '/matching',
  path: '/matching',
  getParentRoute: () => rootRouteImport,
} as any)
const LobbyRoute = LobbyRouteImport.update({
  id: '/lobby',
  path: '/lobby',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteRoute = InviteRouteImport.update({
  id: '/invite',
  path: '/invite',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfirmRoute = ConfirmRouteImport.update({
  id: '/confirm',
  path: '/confirm',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CharacterIdRoute = CharacterIdRouteImport.update({
  id: '/character/$id',
  path: '/character/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/confirm': typeof ConfirmRoute
  '/invite': typeof InviteRoute
  '/lobby': typeof LobbyRoute
  '/matching': typeof MatchingRoute
  '/character/$id': typeof CharacterIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/confirm': typeof ConfirmRoute
  '/invite': typeof InviteRoute
  '/lobby': typeof LobbyRoute
  '/matching': typeof MatchingRoute
  '/character/$id': typeof CharacterIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/confirm': typeof ConfirmRoute
  '/invite': typeof InviteRoute
  '/lobby': typeof LobbyRoute
  '/matching': typeof MatchingRoute
  '/character/$id': typeof CharacterIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/confirm'
    | '/invite'
    | '/lobby'
    | '/matching'
    | '/character/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/confirm' | '/invite' | '/lobby' | '/matching' | '/character/$id'
  id:
    | '__root__'
    | '/'
    | '/confirm'
    | '/invite'
    | '/lobby'
    | '/matching'
    | '/character/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConfirmRoute: typeof ConfirmRoute
  InviteRoute: typeof InviteRoute
  LobbyRoute: typeof LobbyRoute
  MatchingRoute: typeof MatchingRoute
  CharacterIdRoute: typeof CharacterIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/matching': {
      id: '/matching'
      path: '/matching'
      fullPath: '/matching'
      preLoaderRoute: typeof MatchingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lobby': {
      id: '/lobby'
      path: '/lobby'
      fullPath: '/lobby'
      preLoaderRoute: typeof LobbyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite': {
      id: '/invite'
      path: '/invite'
      fullPath: '/invite'
      preLoaderRoute: typeof InviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confirm': {
      id: '/confirm'
      path: '/confirm'
      fullPath: '/confirm'
      preLoaderRoute: typeof ConfirmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/character/$id': {
      id: '/character/$id'
      path: '/character/$id'
      fullPath: '/character/$id'
      preLoaderRoute: typeof CharacterIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConfirmRoute: ConfirmRoute,
  InviteRoute: InviteRoute,
  LobbyRoute: LobbyRoute,
  MatchingRoute: MatchingRoute,
  CharacterIdRoute: CharacterIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
